name: covid_dqn
channels:
  - default
  - conda-forge
  - rdkit
dependencies:
  - python==3.6.*
  - pandas==1.*
  - matplotlib>3
  - rdkit==2019.03.2.0
  - xlrd==1.2.0
  - requests==2.22.0
  - scikit-learn==0.22.*
  - networkx==2.4
  - scipy==1.4.1
  - jupyterlab
  - pytest
  - tqdm
  - h5py
  - pip
  - pip:
    - tensorflow-gpu==2.1.*
    - gym
    - -e .
